### ISSUE TITLE
عوض نشدن قالب سایت

### ISSUE THREAD

**Issue by mehduo** [Ptechgithub/NginxReverseProxy#4]
سلام مرسی بابت اسکریپت عالی که نوشتی❤️
فقط اینکه با انتخاب مجدد گزینه 4 قالب سایت عوض نمیشه

**Comment by Ptechgithub** [comment]
سلام ممنون. عوض میشه ولی به خاطر حافظه ی cache مرورگر  قالب قبلی رو نشون میده روی یه مرورگر دیگه تست کنی میبینی که عوض شده.
