### ISSUE TITLE
لطفا بررسی کنید 

### ISSUE THREAD

**Issue by Feriyali** [Ptechgithub/NginxReverseProxy#6]
سلام خسته نباشید اسکریپت موقع دریافت ssl به مشکل میخوره و نمیتونه ssl بگیر لطفا یه نگاهی بهش بنداز ممنون

**Comment by Ptechgithub** [comment]
سلام چک کردم مشکلی نداره احتمالا چند بار پشت سر هم برای یک ساب دامین سرتیفیکیت گرفتید. یا سرور رو rebuild کنید یا ساب دامین رو عوض کنید

**Comment by Feriyali** [comment]
ممنون از لطف شما و پاسخگویی تست میکنم
