### ISSUE TITLE
مراحل نصب

### ISSUE THREAD

**Issue by Daariush** [Ptechgithub/NginxReverseProxy#8]
برای نصب اسکریپت قبلش لازم هست که پنل x-ui داشته باشیم یا بعدش؟ با هر پنلی کار میکنه؟ در تنظیمات گواهی در پنل باید گواهی که در آخر اسکریپت میده قرار دهیم؟ لطفا یه توضیح اضافه کنید برای این مسائل ممنون

**Comment by Ptechgithub** [comment]
قبل و بعدش زیاد مهم نیست فقط پورت 80 باز باشه که بتونه گواهی بگیره. روی X-ui و 3x-ui تست کردم اوکی بود باقیشو نمیدونم احتمالا جواب بده. در تنظیمات هم بله میتونید گواهی رو قرار بدید.

**Comment by Daariush** [comment]
فقط روی ws تونستم وصل بشم، ولی یه مشکلی که هست اینکه برنامه ایمیل مثل Apple Mail کار نمیکنه و خطای اتصال ssl میده

**Comment by Ptechgithub** [comment]
دقت کن که توی path از / قبل از grpc استفاده نکنی به مثال ها دقت کن که ws علامت / داره ولی grpc نداره

**Comment by Daariush** [comment]
ممنون grpc هم اکی شد، ولی هنوز مشکل اتصال ssl دارم روی email clients و هیچ ایمیلی نه دریافت میشه نه ارسال، یک ربطی باید به tls داشته باشه درسته؟
